### ISSUE TITLE
using contentful plugin breaks the build of the project

### ISSUE THREAD

**Issue by leoparis89** [resir014/gatsby-starter-typescript-plus#10]
using plugin   "gatsby-source-contentful": "^2.1.6"
Gatsby CLI version: 2.7.7
Gatsby version: 2.10.0

I get this error if I add the contentful plugin to this starter and run `gatsby develop`

> 
> error gatsby-node.js returned an error
> 
> 
>   TypeError: Cannot destructure property `slug` of 'undefined' or 'null'.
> 
>   - gatsby-node.js:65 allMarkdown.data.allMarkdownRemark.edges.forEach
>     /Users/me/work/project/gatsby-node.js:65:35
> 
>   - Array.forEach
> 
>   - gatsby-node.js:64 Object.exports.createPages
>     /Users/me/work/project/gatsby-node.js:64:44
> 

I am adding the contentful plugin to gatsby-config.js like follows:

  ```
  {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: 'myId',
        // Learn about environment variables: https://gatsby.dev/env-vars
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
      }
    },
```

What is causing this error ?

**Comment by resir014** [comment]
@leoparis89 When you've deleted all markdown files to use Contentful, you will also need to remove all Remark plugins and code related to generating Markdown pages inside the `gatsby-node.js`.
